os: linux
dist: focal
language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
  - "pypy3.6-7.3.1" #Python 3.6, PyPy 7.3.1
  
before_install:
  - python -m pip install --upgrade pip
  - python3 -m pip install ctgan

install:
  - python3 -m pip install --upgrade SuperconGAN
  - python3 -m pip install --upgrade pytest
  - python3 -m pytest --version

script:
  - python3 -m pytest
