sudo: required
dist: focal # Ubuntu 20.04
language: generic
services: docker # Enables docker

script:
- cd paper
- wget https://raw.githubusercontent.com/blang/latex-docker/master/latexdockercmd.sh
- chmod +x latexdockercmd.sh
- ./latexdockercmd.sh latexmk -pdf -outdir=./_build

deploy:
  provider: releases
  github-token: $GITHUB_TOKEN
  file: "_build/main.pdf"
  skip_cleanup: true
  draft: true
